num_gpus: 1
output_dir: "run"
dataset_name: DD
graphlet_size: 4
model: GNN
gnn_type: "gin"
num_splits: 1
batch_size: 64
lr: 0.005
num_layers: 3
mlp_num_hidden: 1
mlp_hidden_dim: 32
graph_embed_dim: 32
graph_pooling: max
num_epochs: 1000
data_dir: /Users/davidebuffelli/Desktop/data
jk: false
classifier_h_dim: 128
classifier_num_hidden: 1
num_out: 2
classifier_dropout: 0.3
batch_norm:
  presence: true
  affine: false
num_repeat_exp: 50
cmd_reg: true
coarse_ratios: 
  - 0.8
  - 0.9
  #- 0.95
fine_grained_cmd: True
cmd_coeff: 0.1
unc_weight: False
  #gnn_batch_norm: True
normalize_emb: False
coarse_pool: sum
weighted_ce: True
